# telegram-bot/bot/__init__.py
# Estif Bingo 24/7 - Bot Package Initializer
# Initializes the bot package and exports all major components

import logging
from typing import Optional

# Import version info
__version__ = "4.0.0"
__author__ = "Estif Bingo Team"
__description__ = "Telegram Bot for Estif Bingo 24/7 - Real-time Multiplayer Bingo"

# Setup package logger
logger = logging.getLogger(__name__)
logger.info(f"Initializing Estif Bingo Bot v{__version__}")


# ==================== CONFIGURATION ====================

from bot.config import Config, config


# ==================== DATABASE ====================

from bot.db import (
    Database,
    db,
    get_db,
    close_db,
    execute,
    fetch_one,
    fetch_all,
    fetch_val,
    Base,
    # Models
    User,
    AuthCode,
    UserSession,
    Transaction,
    Deposit,
    Withdrawal,
    Transfer,
    Cartela,
    GameRound,
    RoundSelection,
    BonusClaim,
    Tournament,
    TournamentRegistration,
    TournamentPrize,
    AdminLog,
    SystemSetting,
    BroadcastLog,
    Announcement,
    AnnouncementDismissal,
    RateLimit,
    ApiKey,
    SchemaMigration,
    # Repositories
    UserRepository,
    TransactionRepository,
    AuditRepository,
    AuthRepository,
    DepositRepository,
    WithdrawalRepository,
    TransferRepository,
    GameRepository,
    CartelaRepository,
    active_game_cartelas,
    BonusRepository,
    TournamentRepository,
    AdminRepository,
    REPOSITORY_MAP,
    initialize_repositories,
    check_database_health,
    cleanup_old_records,
)


# ==================== GAME ENGINE ====================

from bot.game_engine import (
    BingoRoom,
    GamePhase,
    CartelaManager,
    cartela_manager,
    NumberCaller,
    WeightedNumberCaller,
    create_number_caller,
    WinnerDetector,
    FastWinnerDetector,
    WinPattern,
    create_winner_detector,
    PayoutCalculator,
    create_payout_calculator,
    bingo_room,
    register_socket_events,
    broadcast_cartela_update,
    broadcast_winner_announcement,
    connected_clients,
    init_game_engine,
    shutdown_game_engine,
    get_game_engine_status,
)


# ==================== HANDLERS ====================

from bot.handlers import (
    # Core
    start,
    language_callback,
    help_command,
    about_command,
    # Registration
    register,
    handle_contact,
    register_phone,
    register_cancel,
    # Financial
    balance,
    balance_callback,
    deposit,
    deposit_callback,
    deposit_amount,
    deposit_screenshot,
    deposit_cancel,
    cashout,
    withdrawal_amount,
    withdrawal_method_callback,
    withdrawal_details,
    confirm_withdrawal_callback,
    cancel_withdrawal,
    transfer,
    transfer_phone_number,
    transfer_amount,
    confirm_transfer_callback,
    cancel_transfer_callback,
    cancel_transfer,
    # Game
    play_game,
    game_rules_callback,
    back_to_game_callback,
    quick_deposit_callback,
    mini_bingo,
    play_mini_bingo_callback,
    back_to_mini_bingo_callback,
    bingo_otp,
    verify_otp,
    cancel_otp,
    # Social
    invite,
    copy_invite_link_callback,
    back_to_invite_callback,
    contact_center,
    contact_admin_callback,
    handle_contact_message,
    cancel_contact_callback,
    back_to_menu_callback,
    # Bonus
    bonus,
    claim_welcome_bonus_callback,
    claim_daily_bonus_callback,
    bonus_info_command,
    check_bonus_eligibility,
    grant_bonus,
    # Tournament
    tournament,
    tournament_register_callback,
    tournament_confirm_register_callback,
    tournament_play_callback,
    tournament_leaderboard_callback,
    cancel_tournament_register_callback,
    back_to_tournament_callback,
    admin_create_tournament,
    admin_end_tournament,
    TOURNAMENT_ENABLED,
    # Admin
    admin_command,
    set_win_percent,
    force_start,
    force_stop,
    set_sound_pack,
    search_player,
    stats_command,
    approve_deposit,
    reject_deposit,
    approve_withdrawal,
    reject_withdrawal,
    broadcast_command,
    broadcast_message,
    broadcast_confirm_callback,
    broadcast_cancel_callback,
    maintenance_command,
    reset_game_command,
    cancel_broadcast,
    # Conversation states
    REGISTER_PHONE,
    DEPOSIT_AMOUNT,
    DEPOSIT_SCREENSHOT,
    CASHOUT_AMOUNT,
    CASHOUT_METHOD,
    CASHOUT_ACCOUNT_DETAILS,
    CASHOUT_CONFIRMATION,
    TRANSFER_PHONE_NUMBER,
    TRANSFER_AMOUNT,
    TRANSFER_CONFIRMATION,
    WAITING_FOR_OTP,
    BROADCAST_MESSAGE,
    BROADCAST_CONFIRM,
    # Lists
    CONVERSATION_STATES,
    CONVERSATION_HANDLERS,
    CALLBACK_HANDLERS,
    COMMAND_HANDLERS,
    MESSAGE_HANDLERS,
)


# ==================== API ====================

from bot.api import (
    api_bp,
    game_api_bp,
    webhook_bp,
    commission_bp,
    mini_bingo_bp,
    admin_api_bp,
    register_blueprints,
    rate_limit,
    get_api_version,
    API_VERSION,
    # Auth
    generate_jwt,
    generate_refresh_token,
    verify_jwt,
    refresh_jwt,
    token_required,
    optional_token_required,
    api_key_required,
    generate_ws_token,
    verify_ws_token,
    get_current_user_from_request,
    generate_api_key,
    hash_api_key,
    register_auth_routes,
    # Balance ops
    get_balance,
    add_balance,
    deduct_balance,
    set_balance,
    add_balance_bulk,
    deduct_balance_bulk,
    check_sufficient_balance,
    validate_and_deduct,
    get_balance_history,
    get_balance_summary,
    admin_adjust_balance,
    transfer_balance,
    # Commission
    calculate_commission,
    calculate_round_commission,
)


# ==================== KEYBOARDS ====================

from bot.keyboards import (
    # Main menus
    main_menu_keyboard,
    reply_menu_keyboard,
    deposit_methods_keyboard,
    deposit_amount_keyboard,
    cashout_methods_keyboard,
    cashout_amount_keyboard,
    transfer_amount_keyboard,
    settings_keyboard,
    language_keyboard,
    bonus_keyboard,
    admin_panel_keyboard,
    admin_users_keyboard,
    admin_deposit_keyboard,
    admin_withdrawal_keyboard,
    confirmation_keyboard,
    pagination_keyboard,
    back_to_menu_keyboard,
    cancel_keyboard,
    # Game keyboards
    game_control_keyboard,
    cartela_action_keyboard,
    selection_confirmation_keyboard,
    number_caller_keyboard,
    winner_announcement_keyboard,
    sound_pack_keyboard,
    leaderboard_type_keyboard,
    game_history_keyboard,
    game_control_admin_keyboard,
    win_percentage_keyboard,
    insufficient_balance_keyboard,
    game_in_progress_keyboard,
    # Convenience functions
    get_menu_keyboard,
    get_reply_keyboard,
    get_deposit_keyboard,
    get_cashout_keyboard,
    get_settings_keyboard,
    get_bonus_keyboard,
    get_admin_keyboard,
    get_game_keyboard,
    get_sound_pack_keyboard,
    get_leaderboard_keyboard,
    get_insufficient_balance_keyboard,
    get_game_in_progress_keyboard,
    # Dynamic access
    KEYBOARD_MAP,
    get_keyboard,
)


# ==================== TEXTS ====================

from bot.texts import (
    TEXTS,
    get_text,
    get_emoji,
    EMOJIS,
)


# ==================== UTILS ====================

from bot.utils import (
    # Logger
    setup_logger,
    get_logger,
    # Security
    generate_otp,
    hash_otp,
    verify_otp,
    generate_jwt_for_game,
    generate_ws_token,
    verify_ws_token,
    hash_password,
    verify_password,
    generate_idempotency_key,
    # Crypto
    encrypt_phone,
    decrypt_phone,
    hash_phone,
    encrypt_bank_details,
    decrypt_bank_details,
    # Validators
    is_valid_phone,
    is_valid_ethiopian_phone,
    is_valid_kenyan_phone,
    normalize_phone,
    get_phone_carrier,
    validate_amount,
    validate_account_number,
    validate_transaction_id,
    # Main utils
    truncate_text,
    slugify,
    mask_string,
    mask_phone,
    mask_email,
    format_datetime,
    format_date,
    format_time_remaining,
    time_ago,
    format_currency,
    format_percentage,
    safe_divide,
    generate_token,
    hash_token,
    safe_get,
    merge_dicts,
    retry,
    timing_decorator,
)
from bot.utils.main import generate_reference_id

# ==================== MAIN BOT CLASS ====================

from bot.main import EstifBingoBot, run_bot


# ==================== PACKAGE EXPORTS ====================

__all__ = [
    # Version
    '__version__',
    '__author__',
    '__description__',
    
    # Config
    'Config',
    'config',
    
    # Database
    'Database',
    'db',
    'get_db',
    'close_db',
    'execute',
    'fetch_one',
    'fetch_all',
    'fetch_val',
    'Base',
    'User',
    'AuthCode',
    'UserSession',
    'Transaction',
    'Deposit',
    'Withdrawal',
    'Transfer',
    'Cartela',
    'GameRound',
    'RoundSelection',
    'BonusClaim',
    'Tournament',
    'TournamentRegistration',
    'TournamentPrize',
    'AdminLog',
    'SystemSetting',
    'BroadcastLog',
    'Announcement',
    'AnnouncementDismissal',
    'RateLimit',
    'ApiKey',
    'SchemaMigration',
    'UserRepository',
    'TransactionRepository',
    'AuditRepository',
    'AuthRepository',
    'DepositRepository',
    'WithdrawalRepository',
    'TransferRepository',
    'GameRepository',
    'CartelaRepository',
    'active_game_cartelas',
    'BonusRepository',
    'TournamentRepository',
    'AdminRepository',
    'REPOSITORY_MAP',
    'initialize_repositories',
    'check_database_health',
    'cleanup_old_records',
    
    # Game Engine
    'BingoRoom',
    'GamePhase',
    'CartelaManager',
    'cartela_manager',
    'NumberCaller',
    'WeightedNumberCaller',
    'create_number_caller',
    'WinnerDetector',
    'FastWinnerDetector',
    'WinPattern',
    'create_winner_detector',
    'PayoutCalculator',
    'create_payout_calculator',
    'bingo_room',
    'register_socket_events',
    'broadcast_cartela_update',
    'broadcast_winner_announcement',
    'connected_clients',
    'init_game_engine',
    'shutdown_game_engine',
    'get_game_engine_status',
    
    # Handlers
    'start',
    'language_callback',
    'help_command',
    'about_command',
    'register',
    'handle_contact',
    'register_phone',
    'register_cancel',
    'balance',
    'balance_callback',
    'deposit',
    'deposit_callback',
    'deposit_amount',
    'deposit_screenshot',
    'deposit_cancel',
    'cashout',
    'withdrawal_amount',
    'withdrawal_method_callback',
    'withdrawal_details',
    'confirm_withdrawal_callback',
    'cancel_withdrawal',
    'transfer',
    'transfer_phone_number',
    'transfer_amount',
    'confirm_transfer_callback',
    'cancel_transfer_callback',
    'cancel_transfer',
    'play_game',
    'game_rules_callback',
    'back_to_game_callback',
    'quick_deposit_callback',
    'mini_bingo',
    'play_mini_bingo_callback',
    'back_to_mini_bingo_callback',
    'bingo_otp',
    'verify_otp',
    'cancel_otp',
    'invite',
    'copy_invite_link_callback',
    'back_to_invite_callback',
    'contact_center',
    'contact_admin_callback',
    'handle_contact_message',
    'cancel_contact_callback',
    'back_to_menu_callback',
    'bonus',
    'claim_welcome_bonus_callback',
    'claim_daily_bonus_callback',
    'bonus_info_command',
    'check_bonus_eligibility',
    'grant_bonus',
    'tournament',
    'tournament_register_callback',
    'tournament_confirm_register_callback',
    'tournament_play_callback',
    'tournament_leaderboard_callback',
    'cancel_tournament_register_callback',
    'back_to_tournament_callback',
    'admin_create_tournament',
    'admin_end_tournament',
    'TOURNAMENT_ENABLED',
    'admin_command',
    'set_win_percent',
    'force_start',
    'force_stop',
    'set_sound_pack',
    'search_player',
    'stats_command',
    'approve_deposit',
    'reject_deposit',
    'approve_withdrawal',
    'reject_withdrawal',
    'broadcast_command',
    'broadcast_message',
    'broadcast_confirm_callback',
    'broadcast_cancel_callback',
    'maintenance_command',
    'reset_game_command',
    'cancel_broadcast',
    'REGISTER_PHONE',
    'DEPOSIT_AMOUNT',
    'DEPOSIT_SCREENSHOT',
    'CASHOUT_AMOUNT',
    'CASHOUT_METHOD',
    'CASHOUT_ACCOUNT_DETAILS',
    'CASHOUT_CONFIRMATION',
    'TRANSFER_PHONE_NUMBER',
    'TRANSFER_AMOUNT',
    'TRANSFER_CONFIRMATION',
    'WAITING_FOR_OTP',
    'BROADCAST_MESSAGE',
    'BROADCAST_CONFIRM',
    'CONVERSATION_STATES',
    'CONVERSATION_HANDLERS',
    'CALLBACK_HANDLERS',
    'COMMAND_HANDLERS',
    'MESSAGE_HANDLERS',
    
    # API
    'api_bp',
    'game_api_bp',
    'webhook_bp',
    'commission_bp',
    'mini_bingo_bp',
    'admin_api_bp',
    'register_blueprints',
    'rate_limit',
    'get_api_version',
    'API_VERSION',
    'generate_jwt',
    'generate_refresh_token',
    'verify_jwt',
    'refresh_jwt',
    'token_required',
    'optional_token_required',
    'api_key_required',
    'generate_ws_token',
    'verify_ws_token',
    'get_current_user_from_request',
    'generate_api_key',
    'hash_api_key',
    'register_auth_routes',
    'get_balance',
    'add_balance',
    'deduct_balance',
    'set_balance',
    'add_balance_bulk',
    'deduct_balance_bulk',
    'check_sufficient_balance',
    'validate_and_deduct',
    'get_balance_history',
    'get_balance_summary',
    'admin_adjust_balance',
    'transfer_balance',
    'calculate_commission',
    'calculate_round_commission',
    
    # Keyboards
    'main_menu_keyboard',
    'reply_menu_keyboard',
    'deposit_methods_keyboard',
    'deposit_amount_keyboard',
    'cashout_methods_keyboard',
    'cashout_amount_keyboard',
    'transfer_amount_keyboard',
    'settings_keyboard',
    'language_keyboard',
    'bonus_keyboard',
    'admin_panel_keyboard',
    'admin_users_keyboard',
    'admin_deposit_keyboard',
    'admin_withdrawal_keyboard',
    'confirmation_keyboard',
    'pagination_keyboard',
    'back_to_menu_keyboard',
    'cancel_keyboard',
    'game_control_keyboard',
    'cartela_action_keyboard',
    'selection_confirmation_keyboard',
    'number_caller_keyboard',
    'winner_announcement_keyboard',
    'sound_pack_keyboard',
    'leaderboard_type_keyboard',
    'game_history_keyboard',
    'game_control_admin_keyboard',
    'win_percentage_keyboard',
    'insufficient_balance_keyboard',
    'game_in_progress_keyboard',
    'get_menu_keyboard',
    'get_reply_keyboard',
    'get_deposit_keyboard',
    'get_cashout_keyboard',
    'get_settings_keyboard',
    'get_bonus_keyboard',
    'get_admin_keyboard',
    'get_game_keyboard',
    'get_sound_pack_keyboard',
    'get_leaderboard_keyboard',
    'get_insufficient_balance_keyboard',
    'get_game_in_progress_keyboard',
    'KEYBOARD_MAP',
    'get_keyboard',
    
    # Texts
    'TEXTS',
    'get_text',
    'get_emoji',
    'EMOJIS',
    
    # Utils
    'setup_logger',
    'get_logger',
    'generate_otp',
    'hash_otp',
    'verify_otp',
    'generate_jwt_for_game',
    'generate_ws_token',
    'verify_ws_token',
    'hash_password',
    'verify_password',
    'generate_idempotency_key',
    'encrypt_phone',
    'decrypt_phone',
    'hash_phone',
    'encrypt_bank_details',
    'decrypt_bank_details',
    'is_valid_phone',
    'is_valid_ethiopian_phone',
    'is_valid_kenyan_phone',
    'normalize_phone',
    'get_phone_carrier',
    'validate_amount',
    'validate_account_number',
    'validate_transaction_id',
    'truncate_text',
    'slugify',
    'mask_string',
    'mask_phone',
    'mask_email',
    'format_datetime',
    'format_date',
    'format_time_remaining',
    'time_ago',
    'format_currency',
    'format_percentage',
    'safe_divide',
    'generate_token',
    'generate_reference_id',
    'hash_token',
    'safe_get',
    'merge_dicts',
    'retry',
    'timing_decorator',
    
    # Main Bot
    'EstifBingoBot',
    'create_flask_app',
    'run_bot',
]


# ==================== PACKAGE INITIALIZATION LOG ====================

logger.info(f"Estif Bingo Bot v{__version__} package initialized successfully")